# Adds the Agent0-Lite sidecar as a sibling service without touching your existing stack.
# Safe: isolated container, non-root, healthcheck, fixed port, own network.

services:
  agent0-lite:
    build:
      context: ./agent0-lite          # <-- folder inside ArtifactForge (copy your sidecar here)
      dockerfile: Dockerfile
    container_name: agent0-lite
    restart: unless-stopped
    environment:
      PORT: "4040"
      LOG_LEVEL: "INFO"
      BUILD_VERSION: "phase1-1.0.0"
      CONFIG_PATH: "/app/agent0-lite/config.yaml"
      # Optional for Phase 1; if unset, /health reports "missing_key" but stays up.
      OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
      GROQ_API_KEY:   "${GROQ_API_KEY:-}"
      # Strict egress allowlist:
      ALLOW_PROVIDERS: "openai,groq"
      DENY_PROVIDERS:  "openrouter,anthropic,together,replicate,cohere,gemini"
      ALLOWED_HOSTS:   "api.openai.com,api.groq.com"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:4040/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "4040:4040"
    networks:
      - agent_mesh

networks:
  agent_mesh:
    name: agent_mesh
    driver: bridge
